### ISSUE TITLE
Problems loading icons in Chrome 45 Beta

### ISSUE THREAD

**Issue by Finkelnburg** [digitalfondue/lavagna-docker#1]
Chrome 45 Beta on Ubuntu 14.04 (64-bit) seems to have problems loading icons like "Watch" , "Assign", "Update description", "Edit", etc... Just fragments are shown (if at all) while no problems are visible in Firefox 40 and Chromium 44.

**Comment by syjer** [comment]
Hi @Finkelnburg , thanks for finding this issue, we will do a fix ASAP :)

**Comment by syjer** [comment]
@Finkelnburg it appears to be a bug in chrome 45 : https://code.google.com/p/chromium/issues/detail?id=518121 (the browser does not send the cookie -> the server require authentication -> it will do a redirect to the login page). So in theory, it will be fixed when the next update of the beta version will be pushed.

If you don't mind, can I close the issue?

Thank you :)

**Comment by Finkelnburg** [comment]
@syjer I see. It's not a bug in your code then ;)

Nevertheless, many thanks for investigating this issue so quickly and sharing the infos/results!

**Comment by syjer** [comment]
@Finkelnburg  Well, with your issue I've noticed that some content types were missing (font related), so it was good to check :)
